export { HomeIcon } from './home-icon'
export { PlaneIcon } from './plane-icon'
export { UsersIcon } from './users-icon'
export { UmbrellaIcon } from './umbrella-icon'
export { FlagIcon } from './flag-icon'
